//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogTask.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogsTable
    {
        public int BlogId { get; set; }
        public string BlogTitle { get; set; }
        public string images { get; set; }
        public string messages { get; set; }
        public int UId { get; set; }
        public int ratings { get; set; }
        public string TravelDate { get; set; }
    
        public virtual UserTable UserTable { get; set; }
    }
}
