//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionBankApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question_Table1
    {
        public int QuestionId { get; set; }
        public string Question { get; set; }
        public string Keyword { get; set; }
        public int SubjectType { get; set; }
        public string Option1 { get; set; }
        public string Option2 { get; set; }
        public string Option3 { get; set; }
        public string Option4 { get; set; }
    
        public virtual SubjectTable1 SubjectTable1 { get; set; }
    }
}
